#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'ZhuangBei' do
  pod 'PPNetworkHelper',:git => 'https://github.com/jkpang/PPNetworkHelper.git'
  pod "Masonry"
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
end   

