#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
#platform :ios, '7.0'

target 'ZhuangBei' do
  pod "Masonry"
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'MJExtension'
  pod 'YYKit'
  pod 'AFNetworking', '~> 3.0'
  pod 'SDCycleScrollView','>= 1.80'
  pod 'TYAttributedLabel'
  pod 'LEEAlert'
  pod "UITextView-WZB","1.1.1"
  pod 'JShare'
  pod 'SVGKit'
  pod 'WMZBanner'
  pod 'ReactiveObjC'
  pod 'UMCCommon'
  pod 'UMCPush'
  pod 'UMCCommonLog'
  pod 'UMCSecurityPlugins'
end   

